import type { AppLocale } from '@/types/appSettings';

const copy = {
  ru: {
    loginTitle: 'Войдите в свой аккаунт',
    registerTitle: 'Начни свой путь к идеальной работе',
    forgotSentTitle: 'Проверьте почту',
    forgotTitle: 'Забыли пароль?',
    loginSubtitle: 'Войдите, чтобы продолжить работу с LEO',
    registerSubtitle: 'Зарегистрируйся и начни диалог с LEO уже сегодня',
    forgotSentSubtitle: (email: string) =>
      `Если аккаунт ${email} существует, мы отправили ссылку для сброса пароля. Ссылка действует 1 час.`,
    forgotSubtitle: 'Введите email — отправим ссылку для сброса пароля',
    tabLogin: 'Вход',
    tabRegister: 'Регистрация',
    emailRequired: 'Введите email',
    emailInvalid: 'Введите корректный email',
    passwordRequired: 'Введите пароль',
    passwordMin: 'Пароль должен быть не менее 6 символов',
    passwordLoginPlaceholder: 'Ваш пароль',
    passwordRegisterPlaceholder: 'Минимум 6 символов',
    forgotLink: 'Забыли пароль?',
    submitLogin: 'Войти',
    submitRegister: 'Зарегистрироваться',
    orContinue: 'или продолжить через',
    yandexLogin: 'Войти через Яндекс ID',
    sendResetLink: 'Отправить ссылку',
    backToLogin: '← Вернуться ко входу',
    backToLoginBtn: 'Вернуться ко входу',
    resendLink: 'Отправить ссылку ещё раз',
    loginSuccess: 'Вход выполнен успешно!',
    registerSuccess: 'Регистрация успешна!',
    loginError: 'Ошибка входа',
    registerError: 'Ошибка регистрации',
    forgotError: 'Не удалось отправить письмо',
  },
  en: {
    loginTitle: 'Sign in to your account',
    registerTitle: 'Start your path to the right job',
    forgotSentTitle: 'Check your email',
    forgotTitle: 'Forgot password?',
    loginSubtitle: 'Sign in to continue with LEO',
    registerSubtitle: 'Register and start chatting with LEO today',
    forgotSentSubtitle: (email: string) =>
      `If an account exists for ${email}, we sent a reset link. It is valid for 1 hour.`,
    forgotSubtitle: 'Enter your email — we’ll send a reset link',
    tabLogin: 'Log in',
    tabRegister: 'Sign up',
    emailRequired: 'Enter your email',
    emailInvalid: 'Enter a valid email',
    passwordRequired: 'Enter your password',
    passwordMin: 'Password must be at least 6 characters',
    passwordLoginPlaceholder: 'Your password',
    passwordRegisterPlaceholder: 'At least 6 characters',
    forgotLink: 'Forgot password?',
    submitLogin: 'Sign in',
    submitRegister: 'Sign up',
    orContinue: 'or continue with',
    yandexLogin: 'Sign in with Yandex ID',
    sendResetLink: 'Send reset link',
    backToLogin: '← Back to sign in',
    backToLoginBtn: 'Back to sign in',
    resendLink: 'Send link again',
    loginSuccess: 'Signed in successfully!',
    registerSuccess: 'Registration successful!',
    loginError: 'Sign-in failed',
    registerError: 'Registration failed',
    forgotError: 'Could not send the email',
  },
} as const;

export function authUi(locale: AppLocale) {
  return copy[locale];
}
